version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb_framework
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - mariadb_framework_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_framework
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_framework_data:/data
    command: redis-server --appendonly yes

volumes:
  mariadb_framework_data:
  redis_framework_data: